# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  # Vagrant box - образ ОС из которой
  # будет создана виртуальная машина.
  # Список образов на https://app.vagrantup.com/boxes/search
  # Здесь используется Ubuntu Server 14.04 LTS
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure=true

  # Отключает автоматическое обновление образов.
  config.vm.box_check_update = true
  
 

  # Настройки виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    # Показывать или нет интерфейс VirtualBox при загрузке.
    vb.gui = false
	# Выделяемая память для виртуалки.
	vb.memory = "1024"
	# Название в интерфейсе VirtualBox.
	vb.name = "vagrant_test"
	 
    # Сценарий настройки виртуальной машины
  config.vm.provision "shell", inline: <<-SHELL
    # Обновление списка пакетов и установка PostgreSQL 8.4
    sudo touch /etc/apt/sources.list.d/pgdg.list
    sudo echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install postgresql-8.4

    # Создание и настройка пользователя postgres
    sudo -u postgres createuser --createdb --password postgres
    sudo -u postgres psql -c "alter user postgres with password 'password';"

    # Разрешение удаленного подключения к PostgreSQL
    echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/8.4/main/pg_hba.conf > /dev/null
    echo "listen_addresses='*'" | sudo tee -a /etc/postgresql/8.4/main/postgresql.conf > /dev/null

    # Перезапуск PostgreSQL
    sudo service postgresql restart
    # Проверка установки и работоспособности PostgreSQL
    sudo -u postgres psql -c "SELECT version();"
    SHELL
  end  

end